### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Apaapi\operations\SearchItems' not found

### ISSUE THREAD

**Issue by jiiins** [Jakiboy/apaapi#1]
I'm trying to run example.php on a system where I can't run compose.

How can I avoid the above error? Sorry but my PHP knowledge is really tiny.

**Comment by Jakiboy** [comment]
Yep 😊 thats why you have the error, you need to use composer.
Anyway, here is the uploaded production files for **testing**, Please replace {Your-partner-tag}, {Your-keywords}, {Your-key-id}, {Your-secrect-key} & {your-region}.

Invalid credentials means : No response, 
else you'll get JSON response of requested amazon product with all you need, Name, Price, Images... Usin Keyword or ASIN method.

Your can run it via a Web Server (127.0.0.1/exemple.php), or Basically via PHP CLI (php exemple.php).

Hope this can help.
JS
[example.zip](https://github.com/Jakiboy/apaapi/files/4206072/example.zip)

**Comment by jiiins** [comment]
Perfect, thanks a lot!

**Comment by jiiins** [comment]
Hi Jakiboy,

if I upgrade to 1.0.6 I get the following error when calling from my external function:

PHP Fatal error:  Uncaught Error: Cannot access private property Apaapi\lib\Response::$body

I looked at the code but can figure this out...

**Comment by Jakiboy** [comment]
Hey,
Please send your "calling" code so i can find out the issus, and change it

**Comment by jiiins** [comment]
Hey,

the code is attached.

Thanks!
[amazon-demo.txt](https://github.com/Jakiboy/apaapi/files/4731200/amazon-demo.txt)

**Comment by Jakiboy** [comment]
[Test-Updated.zip](https://github.com/Jakiboy/apaapi/files/4740506/Test-Updated.zip)
Test Updated ^^

**Comment by gnadelwartz** [comment]
I had the same Problem after updating, maybe you should mention to replace response->body with response->get () ehrn updating from 1.0.4 to a newer version.

I noticed this by looking on commit to example.php  https://github.com/Jakiboy/apaapi/commit/49d87f5d1af94675e482a69c556022105cda85c1 only
