### ISSUE TITLE
Set curl timeout

### ISSUE THREAD

**Issue by gnadelwartz** [Jakiboy/apaapi#2]
currently I have the issue tha amazon.fr api waits forever without an respone.

I found no way to set a TIMEOUT for your lib when query amazon, so I added the following line manually to 'RequestClient.php' to work around the issue.

``` php
curl_setopt($this->handler, CURLOPT_TIMEOUT, 10);
```
I would be nice if you can implement a parameter to set the timeout.

**Comment by Jakiboy** [comment]
Will update soon

**Comment by Jakiboy** [comment]
Line added
