### ISSUE TITLE
Uncaught Error: Cannot access private property $body

### ISSUE THREAD

**Issue by equisele** [Jakiboy/apaapi#3]
Hi there,

First of all, great job for making a simplest Amazon API 5 wrapper 👍 

I'v found an issue when I tested with test.php throwing an error cause $body was private instead of public so it's not possible

(https://github.com/Jakiboy/apaapi/blob/8e1c0eed9af1e937cf991f054b09a42d26acc7b4/src/lib/Response.php#L28)

Again, thanks for this great job!

Regards,

**Comment by Jakiboy** [comment]
Hello Ángel,
Thank you, My pleasure...
To get the response you can use public **get** Method, it'll return the **$body**

Tell me if there is anything else.

Thank you
JS

**Comment by Jakiboy** [comment]
I have also edited the test/example.php
