### ISSUE TITLE
Retrun paapi errors messages from amazon istead your own ...

### ISSUE THREAD

**Issue by gnadelwartz** [Jakiboy/apaapi#4]
I was wondering about the error messages returned by apaapi and found you return fixes error messages based on https error.

If paapi returns a known error (400, 401, 403, 429) it returns also a detailed error response, see https://webservices.amazon.com/paapi5/documentation/troubleshooting/error-messages.html#sample-error-scenarios

you can return this respose as error message instead using the fixed ones in RequestClient.php:
```php
 		if ( $this->getHttpCode() == 400 ) {
			$this->error = 'The partner tag is not mapped to a valid associate store with your access key';
		} elseif {
			 ...
		}
```
example code  to return paapi response:

```php
 		switch ( $this->getHttpCode() ) {
			case 400:
			case 401:
			case 403:
			case 429:
				$this->error = $this->body;
				$this->body=false;
				break;
			default:
				$this->error = 'Unestablished Server Connection';
		}
```

EDIT: to make this work, you have to get body always :-)
```php
                      // Get Amazon JSON response
                        $this->body = $reponse;
                        if ( $this->getHttpCode() != 200 ) {
                                // Set Amazon API errors
                                $this->setHttpError();
                        }
```
After implementing this, I saw the real error instead of the one provided by `apappi` and can react accordingly

```
The request was denied due to request throttling. Please verify the number of requests made per second to the Amazon Product Advertising API
```

**Comment by gnadelwartz** [comment]
While testing this, I found an other "advatage" I like, you get the paapi error respose also if you don't check for errors as you get other error responses from paapi. 

What I did not check for this quick hack is: do we need to check for unkown http error codes before calling

 ```php
$this-body = $ response
```

**Comment by gnadelwartz** [comment]
ecample output with a wrong partner ID:
```bash
# old
$> amazon.php tag=123456-21
The partner tag is not mapped to a valid associate store with your access key

# new
$> amazon.php tag=123456-21
{"__type":"com.amazon.paapi5#InvalidPartnerTagException","Errors":[{"Code":"InvalidPartnerTag","Message":"The partner tag is not mapped to a valid associate store with your access key XXXXXXXXXXXXXX. Please visit associates central at https://partnernet.amazon.de/assoc_credentials/home"}]}
```

**Comment by gnadelwartz** [comment]
And while I'm looking at the code, I got the idea to include the http response code always:

```php
$this->body = rtrim($reponse, '} ').',"Http":{"ResponseCode":'.$this->getHttpCode() . '}}';
```
you may find at least some of my ideas useful ...

**Comment by Jakiboy** [comment]
Thanks for your work, Agree, Reviewing the pull and I'll submit it ASAP
