### ISSUE TITLE
How to add custom Parameter like "SearchIndex"

### ISSUE THREAD

**Issue by kbtonmoy** [Jakiboy/apaapi#7]
Hi, 
Thank you for the awesome package. I have been using it for a long time. I have a query and badly need some help. 
How can I add "SearchIndex" parameter to the payload? 
Currently, I'm using this demo:
` // (1) Set Operation
        $operation = new SearchItems();
        $operation->setPartnerTag($partnerTag)->setKeywords($keyword);

        // (2) Prapere Request
        $request = new Request($api_key, $secret_key);
        $request->setLocale($host)->setPayload($operation)->setSearchIndex();

        // (3) Get Response
        $response = new Response($request);
        $abs = json_decode($response->get(), true);`

**Comment by Jakiboy** [comment]
Hey @kbtonmoy 

Juste add the SearchIndex before payload, as written below:

```php
// (1) Set Operation
$operation = new SearchItems();
$operation->setPartnerTag('{Your-partner-tag}')->setKeywords('{Your-keywords}');

// Here: You can add SearchIndex (before payload)
$operation->setSearchIndex('Electronics');

// (2) Prapere Request
$request = new Request('{Your-key-id}','{Your-secrect-key}');
$request->setLocale('{Your-region}')->setPayload($operation);

// (3) Get Response
$response = new Response($request);
echo $response->get(); // JSON ready for parsing

```

**Comment by kbtonmoy** [comment]
Thanks man!  Sent from Mail for Windows From: JIHAD SINNAOURSent: Wednesday, October 19, 2022 1:53 AMTo: Jakiboy/apaapiCc: Khabirul Basar; MentionSubject: Re: [Jakiboy/apaapi] How to add custom Parameter like "SearchIndex" (Issue #7) Hey @kbtonmoyJuste add the SearchIndex before payload, as written below:// (1) Set Operation$operation = new SearchItems();$operation->setPartnerTag('{Your-partner-tag}')->setKeywords('{Your-keywords}'); // Here: You can add SearchIndex (before payload)$operation->setSearchIndex('Electronics'); // (2) Prapere Request$request = new Request('{Your-key-id}','{Your-secrect-key}');$request->setLocale('{Your-region}')->setPayload($operation); // (3) Get Response$response = new Response($request);echo $response->get(); // JSON ready for parsing—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Jakiboy** [comment]
Welcome!
