### ISSUE TITLE
I want to Request with Page / Pagination

### ISSUE THREAD

**Issue by muazinasro** [Jakiboy/apaapi#8]
How to request with page 2, 3 and 4 etc...

**Comment by Jakiboy** [comment]
pagination is not available right now, 
maybe w'll add it later...
According to UX, users are often choosing the first result..

**Comment by jonrodsan** [comment]
When you are preparing the search just call the method `setItemPage()` like this:

```
$operation = new SearchItems();
$operation->setPartnerTag($partner_tag)
          ->setKeywords($keywords)
          ->setItemPage($page);
```
You must make the pagination system yourself. 

Consider Amazon Products API only returns a maximum of 10 pages, even it say it has thousand of results.

**Comment by Jakiboy** [comment]
@muazinasro best response is gived by @jonrodsan 
I'm closing this issue for now. Feel free to reopen it if needed.

**Comment by muazinasro** [comment]
Thank You... Resolved.
