### ISSUE TITLE
I need your help so I can at least understand something

### ISSUE THREAD

**Issue by Presenze** [Jakiboy/apaapi#9]
Hi, I'm a beginner, in fact I'm not able to understand the procedures to make everything work, that is, are the files complete? How do I connect everything and see a search bar on the screen looking for Amazon products? do I create an html page? I'm sorry but I can't find a tutorial that explains everything, could you help me please? Thank you, you are very kind

**Comment by Jakiboy** [comment]
Hello, Sure no problem.

First, this a PHP library, Means a script handled and executed by **PHP language interpreter**,
So its requires:

1- Server Side Environment (Apache),
2- An installed PHP program (V7.x).

You will need to create an index file "_index.php_" (that includes the HTML search bar for example),
Then create a second file "_search.php_" Where you pur logical using **Apaapi**.

This files should be uploaded in server, Or you can use a local server (In your machine).

Please see the example i juste create "_example.zip_"
Note : You need [Amazon Product Advertising API](https://webservices.amazon.com/paapi5/documentation/register-for-pa-api.html) Credentials to make it working!

Have a good day :)
[example.zip](https://github.com/Jakiboy/apaapi/files/12890793/example.zip)

**Comment by Presenze** [comment]
first of all thanks for your answer, so I'm using xaamp as a server, I've loaded your entire project now I create an html page and insert any search bar? example .....

<form action="https://www.amazon.com/s" method="GET">
        <input type="text" name="field-keywords" placeholder="Cerca su Amazon...">
        <button type="submit">Cerca</button>
    </form>

 then how do I connect everything? I have the API keys, should I insert them from your correct file? thank you dear, I hope I don't bother you with these beginner questions... 

if you like, reply to me here, my email frequentation0misteriose@gmail.com
maybe send me an example since I'm really handicapped, thank you very much indeed

**Comment by Jakiboy** [comment]
Hello,
Xaamp is good,

Yes you need to fill in the API credentials in the example I sent you. Put everything in the right place:

- YOUR-PARTNER-TAG
- YOUR-KEY-ID
- YOUR-SECRECT-KEY
- YOUR-REGION

Note: the exemple i sent is a working prov of concept.

**Comment by Presenze** [comment]
it gives me this error did I do something wrong?

setPartnerTag('codiciscon0f8-21')->setKeywords($_POST['product']); // (2) Prapere Request $request = new Request('AKIAJXXX....', 'BlqW....'); $request->setLocale('IT')->setPayload($operation); // (3) Get Response $response = new Response($request, new ResponseType('array'), Response::PARSE); var_dump($response->get()); // Array ready to be used die(); } ?>

**Comment by Presenze** [comment]
yes I saw your project obviously I have to move the credentials to another file in the index and easily available, however I don't know why it doesn't work I put the credentials

**Comment by Presenze** [comment]
Fatal error: Uncaught Apaapi\exceptions\RequestException: Invalid request locale 'your-region' in C:\Users\UTENTE\Desktop\xaamp\htdocs\example\apaapi\src\lib\Request.php:236 Stack trace: #0 C:\Users\UTENTE\Desktop\xaamp\htdocs\example\index.php(25): Apaapi\lib\Request->setLocale('your-region') #1 {main} thrown in C:\Users\UTENTE\Desktop\xaamp\htdocs\example\apaapi\src\lib\Request.php on line 236

my locate italia so IT correct not work

**Comment by Presenze** [comment]
ok it went thanks but you can't see the products it comes out like this

array(10) { [0]=> array(7) { ["ASIN"]=> string(10) "B08LZJ2H9S" ["BrowseNodeInfo"]=> array(2) { ["BrowseNodes"]=> array(4) { [0]=> array(6) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(3) { ["ContextFreeName"]=> string(11) "Informatica" ["DisplayName"]=> string(11) "Informatica" ["Id"]=> string(9) "425916031" } ["ContextFreeName"]=> string(11) "Informatica" ["DisplayName"]=> string(9) "Categorie" ["Id"]=> string(9) "425917031" } ["ContextFreeName"]=> string(19) "Periferiche di rete" ["DisplayName"]=> string(19) "Periferiche di rete" ["Id"]=> string(9) "460161031" } ["ContextFreeName"]=> string(20) "Hub di rete e switch" ["DisplayName"]=> string(20) "Hub di rete e switch" ["Id"]=> string(9) "460169031" ["IsRoot"]=> bool(false) ["SalesRank"]=> int(27) } [1]=> array(5) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(3) { ["ContextFreeName"]=> string(11) "Informatica" ["DisplayName"]=> string(11) "Informatica" ["Id"]=> string(9) "425916031" } ["ContextFreeName"]=> string(27) "Arborist Merchandising Root" ["DisplayName"]=> string(27) "Arborist Merchandising Root" ["Id"]=> string(11) "89688360031" } ["ContextFreeName"]=> string(12) "Self Service" ["DisplayName"]=> string(12) "Self Service" ["Id"]=> string(9) "518380031" } ["ContextFreeName"]=> string(23) "Special Features Stores" ["DisplayName"]=> string(23) "Special Features Stores" ["Id"]=> string(9) "518382031" } ["ContextFreeName"]=> string(38) "4fc48982-1533-4f34-b83d-7260b28c9fff_0" ["DisplayName"]=> string(38) "4fc48982-1533-4f34-b83d-7260b28c9fff_0" ["Id"]=> string(11) "89688367031" } ["ContextFreeName"]=> string(38) "4fc48982-1533-4f34-b83d-7260b28c9fff_1" ["DisplayName"]=> string(38) "4fc48982-1533-4f34-b83d-7260b28c9fff_1" ["Id"]=> string(11) "89688729031" } ["ContextFreeName"]=> string(19) "Periferiche di rete" ["DisplayName"]=> string(19) "Periferiche di rete" ["Id"]=> string(11) "21357233031" ["IsRoot"]=> bool(false) } [2]=> array(5) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(4) { ["Ancestor"]=> array(3) { ["ContextFreeName"]=> string(11) "Informatica" ["DisplayName"]=> string(11) "Informatica" ["Id"]=> string(9) "425916031" } ["ContextFreeName"]=> string(27) "Arborist Merchandising Root" ["DisplayName"]=> string(27) "Arborist Merchandising Root" ["Id"]=> string(11) "89688360031" } ["ContextFreeName"]=> string(12) "Self Service" ["DisplayName"]=> string(12) "Self Service" ["Id"]=> string(9) "518380031" } ["ContextFreeName"]=> string(23) "Special Features Stores" ["DisplayName"]=> string(23) "Special Features Stores" ["Id"]=> string(9) "518382031" } ["ContextFreeName"]=> string(38) "4fc48

**Comment by Jakiboy** [comment]
Well, Nice progress! you got results

I'll send you a modified version of the example so you can display the product...

**Comment by Presenze** [comment]
thank you my friend you are really smart without you I wouldn't have succeeded

**Comment by Jakiboy** [comment]
Hey,

I updated the example, this all i can do, i hope this will be helpful for you.
[example-v2.zip](https://github.com/Jakiboy/apaapi/files/12906610/example-v2.zip)

Have a good day.

**Comment by Presenze** [comment]
thank you dear it works correctly, obviously I should fix it to make the products come out sorted and aligned with a div?

one last thing I would also like to implement the discount code function and is it possible in the code, for example the user searches for a product and maybe make a coupon appear?

Now I give you 5 stars friend

**Comment by Presenze** [comment]
Parse error: syntax error, unexpected token "<", expecting end of file in C:\Users\UTENTE\Desktop\xaamp\htdocs\example-v2\index.php on line 55

$title = $product['ItemInfo']['Title']['DisplayValue'] ?? '';

it gives me this error it would be this line but there is no error bho
